### ISSUE TITLE
Simple latex 

### ISSUE THREAD

**Issue by yhl48** [phfaist/pylatexenc#109]
Thanks for the great library, is there a way to use `unicode_to_latex` to get a simple character form, for example, `x` instead of `\ensuremath{\mathit{x}}`?

**Comment by phfaist** [comment]
Sure, you can define your own `UnicodeToLatexConversionRule` (see https://pylatexenc.readthedocs.io/en/latest/latexencode/) with either a RULE_DICT rule type and a manual mapping for a subset of the characters you're interested in (e.g. the mathematical letters), or a RULE_REGEX or RULE_CALLABLE with some logic to replace a set of input characters.

**Comment by gy-mate** [comment]
@phfaist I think a simple option to disable the addition of only these commands would be awesome. (E.g. because the MediaWiki [Math extension](https://www.mediawiki.org/wiki/Extension:Math) doesn't recognize `\ensuremath{}`. <img width="500" alt="Screenshot 2024-07-17 at 08 11 32" src="https://github.com/user-attachments/assets/f9b3f4ed-1604-40e8-abc4-ac2db870ebbc">)

**Comment by phfaist** [comment]
do you mean in the command line tool or in the API?

**Comment by gy-mate** [comment]
@phfaist In the API.
