### ISSUE TITLE
Quotation marks

### ISSUE THREAD

**Issue by glostis** [phfaist/pylatexenc#27]
Thanks for the great package!

I am facing an issue with the way quotation marks are parsed using `unicode_to_latex`.

See the following example:
```python
>>> from pylatexenc.latexencode import unicode_to_latex
>>> print(unicode_to_latex('Hello "world".'))
Hello ''world''.
```

Whereas I would expect to get
```python
Hello ``world''.
```

because in LaTeX left quotation marks are represented by backticks (per https://www.maths.tcd.ie/~dwilkins/LaTeXPrimer/QuotDash.html for example).

Is this an issue that can easily be solved?

**Comment by glostis** [comment]
From what I saw by quickly going through the code, the replacement of `"` by `''` is done here: https://github.com/phfaist/pylatexenc/blob/7b44351acecf305873023c1b7c667518b0e0b64a/pylatexenc/latexencode/_uni2latexmap.py#L61

Since you replace single characters, I understand why you cannot distinguish left quotation marks from right quotation marks.

Do you think there's a way to do it with the existing code, or would it require additional development?

**Comment by glostis** [comment]
Actually I think I have found the answer to my own question.
What I want can be achieved by adding a custom regex rule:
```python
import re

from pylatexenc.latexencode import RULE_REGEX, UnicodeToLatexConversionRule, UnicodeToLatexEncoder

u = UnicodeToLatexEncoder(
    conversion_rules=[
        UnicodeToLatexConversionRule(
            rule_type=RULE_REGEX, rule=[(re.compile(r"\"(.*?)\""), r"``\1''")]
        ),
        "defaults",
    ]
)
print(u.unicode_to_latex('Hello "world".'))
# This prints: Hello ``world''.
```

**Comment by phfaist** [comment]
Yes, I've meant to keep the `pylatexenc.latexencode` package simple (to avoid slowing it down) and that's why the encoding is done character-by-character using a python dictionary lookup by default. But your issue is also exactly the type of reason why I recently revised the package and added support for more interesting rules, such as REGEX rules or callback rules. As you noticed, they are more powerful, but the regex is tested at each point in the string which can slow down the encoding. Thanks for your interest in `pylatexenc`!
