### ISSUE TITLE
LatexMathNode is reasonable for '$****$$****$**'

### ISSUE THREAD

**Issue by xiejianping-0108** [phfaist/pylatexenc#43]
Dear Philippe
Thanks for your work!
The lib help me a lot.
I have a question when I use LatexWalker  module to parse a Latex String, it see all text to a LatexMathNode.For example, the following Latex code is part of article:

`\author[$\dagger$$\ddagger$1]{Qinyuan REN}
\author[1]{Ping LI}
%\author[$\dagger$1]{Ping Li}
\affil[1]{State Key Laboratory of Industrial Control Technology, Zhejiang University, Hangzhou 310027, China}
\affil[2]{Department of Electrical and Computer Engineering, National University of Singapore, Singapore 117576, Singapore}
\affil[3]{Zhejiang University of Science and Technology, Hangzhou 310023, China}`

I don't kown is it reasonable, but it is a trouble for me with parse Latex code.
Thanks in advance!

**Comment by phfaist** [comment]
Hi, thanks for the report. I think I see what the bug is—the two consecutive dollar signs in `$\dagger$$\dagger$` are being parsed as a display equation delimiter. The issue is that currently, the tokenizer does not know if we are currently in an inline-math or display-math mode to decide whether to parse two dollar signs as two `$` tokens or a single `$$` token. I'll look a bit deeper into this. As a workaround, if you know you are not parsing any display equations (it looks like you're parsing author/affiliations which probably will never have display equations), you can replace occurences of `$$` by `$ $` (ie with a space between the dollar signs).

**Comment by phfaist** [comment]
I pushed a fix, feel free to re-open this issue if the problem persists in the latest git version.

**Comment by xiejianping-0108** [comment]
> Hi, thanks for the report. I think I see what the bug is—the two consecutive dollar signs in $\dagger$$\dagger$ are being parsed as a display equation delimiter. The issue is that currently, the tokenizer does not know if we are currently in an inline-math or display-math mode to decide whether to parse two dollar signs as two $ tokens or a single $$ token. I'll look a bit deeper into this. As a workaround, if you know you are not parsing any display equations (it looks like you're parsing author/affiliations which probably will never have display equations), you can replace occurences of $$ by $ $ (ie with a space between the dollar signs).

thank you very much!  I have do with you say.
